# CI / CD for keydb-redisjson

name: 'build'

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: "Build:checkout"
        uses: actions/checkout@v2
      - name: "Build:dockerlogin"
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: pr0ton11
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: "Build:dockerimage"
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/pr0ton11/doh:latest
